name: Close Pull Requests from cpanel/elevate
on:
  pull_request:
    types: [opened]

jobs:
  close_pr:
    if: github.event.pull_request.head.repo.full_name == 'cpanel/elevate'
    runs-on: ubuntu-latest
    steps:
      - name: Close the PR
        uses: peter-evans/close-pull@v2
        with:
          comment: "This repository does not accept pull requests from cpanel/elevate."
